#!/usr/bin/env bash
# Copyright (c) 2026 Nyx Software, LLC
# SPDX-License-Identifier: Apache-2.0
# Nyx Backup Recovery - https://nyxbackup.com
#
# Build the standalone Nyx Backup Recovery installer for macOS Apple Silicon.
#
# This is the macOS analogue of:
#   scripts/windows/build_recover_msi_x86_64.sh
#   scripts/linux/build_recover_deb_x86_64.sh
#
# Recovery ships as its own .pkg with a separate UpgradeCode (here: a
# distinct bundle identifier com.nyxbackup.recover) so users can install
# it onto a bare rescue machine, and so "the backup machine is gone"
# scenarios stay covered.
#
# Output: dist/NyxBackup-Recovery-VERSION-arm64.pkg
#
# Usage:
#   scripts/macos/build_recover_pkg_arm64.sh                # compile + package
#   scripts/macos/build_recover_pkg_arm64.sh --skip-build   # use already-staged binary

set -euo pipefail

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# ARCH defaults to arm64.  Setting ARCH=x86_64 (the build_recover_pkg
# _x86_64.sh wrapper does this) swaps the cargo target triple and
# staging path; the rest of the script (Info.plist, codesign,
# productbuild, notarytool) is identical.
ARCH="${ARCH:-arm64}"
case "$ARCH" in
    arm64)  TARGET="aarch64-apple-darwin" ;;
    x86_64) TARGET="x86_64-apple-darwin"  ;;
    *)      echo "Unsupported ARCH=$ARCH (expected arm64 or x86_64)" >&2; exit 1 ;;
esac
PROFILE="${PROFILE:-release}"
STAGING="${WORKSPACE_DIR}/staging/macos/${ARCH}"
DIST="${WORKSPACE_DIR}/dist"

SKIP_BUILD=0
for arg in "$@"; do
    case "$arg" in
        --skip-build) SKIP_BUILD=1 ;;
        *) echo "Unknown argument: $arg"; exit 1 ;;
    esac
done

if [[ "$(uname)" != "Darwin" ]]; then
    echo "ERROR: macOS packaging must run on a Mac (uname=$(uname))."
    exit 1
fi

VERSION=$(tr -d '[:space:]' < "${WORKSPACE_DIR}/VERSION")
BUNDLE_ID="com.nyxbackup.recover"   # matches tauri.conf.json
APP_NAME="Nyx Backup Recovery"
PKG_NAME="NyxBackup-Recovery-${VERSION}-${ARCH}"

echo "Building ${ARCH} Recovery .pkg for Nyx Backup v${VERSION}..."

# ── Source .env for the OAuth secrets the recover binary embeds ──────────────

if [[ -f "${WORKSPACE_DIR}/.env" ]]; then
    set -a; source "${WORKSPACE_DIR}/.env"; set +a
fi
: "${GOOGLE_OAUTH_CLIENT_ID:?Set GOOGLE_OAUTH_CLIENT_ID in .env or the environment}"
: "${GOOGLE_OAUTH_CLIENT_SECRET:?Set GOOGLE_OAUTH_CLIENT_SECRET in .env or the environment}"
: "${DROPBOX_APP_KEY:?Set DROPBOX_APP_KEY in .env or the environment}"
: "${DROPBOX_APP_SECRET:?Set DROPBOX_APP_SECRET in .env or the environment}"
: "${ONEDRIVE_OAUTH_CLIENT_ID:?Set ONEDRIVE_OAUTH_CLIENT_ID in .env or the environment}"
export ONEDRIVE_OAUTH_CLIENT_SECRET="${ONEDRIVE_OAUTH_CLIENT_SECRET:-}"

# ── Compile the recovery binary ──────────────────────────────────────────────

if [[ $SKIP_BUILD -eq 0 ]]; then
    rustup target list --installed | grep -q "$TARGET" || rustup target add "$TARGET"

    # Tauri frontend (separate Svelte project under crates/bkp-recover/ui/).
    if [[ -d "${WORKSPACE_DIR}/crates/bkp-recover/ui" ]]; then
        echo "Building recover frontend..."
        cd "${WORKSPACE_DIR}/crates/bkp-recover/ui"
        npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -3
        npm run build
        cd "$WORKSPACE_DIR"
    fi

    echo "Building nyx_bkp_recover for ${TARGET} (${PROFILE})..."
    cargo build --target "$TARGET" --release \
        -p bkp-recover --bin nyx_bkp_recover

    mkdir -p "$STAGING"
    cp "${WORKSPACE_DIR}/target/${TARGET}/${PROFILE}/nyx_bkp_recover" "$STAGING/"
fi

[[ -f "$STAGING/nyx_bkp_recover" ]] || {
    echo "ERROR: $STAGING/nyx_bkp_recover not found."
    echo "  Run without --skip-build, or stage the binary first."
    exit 1
}

# ── Build Nyx Backup Recovery.app bundle ─────────────────────────────────────

APP_DIR="${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/${APP_NAME}.app"
rm -rf "$APP_DIR"
mkdir -p "${APP_DIR}/Contents/MacOS"
mkdir -p "${APP_DIR}/Contents/Resources"

cp "$STAGING/nyx_bkp_recover" "${APP_DIR}/Contents/MacOS/nyx_bkp_recover"
chmod 0755 "${APP_DIR}/Contents/MacOS/nyx_bkp_recover"

# The recovery app's icon.  Generated by
# scripts/macos/generate_recover_icon.sh.
if [[ -f "${WORKSPACE_DIR}/crates/bkp-recover/icons/icon.icns" ]]; then
    cp "${WORKSPACE_DIR}/crates/bkp-recover/icons/icon.icns" \
       "${APP_DIR}/Contents/Resources/AppIcon.icns"
else
    echo "WARN: recovery icon not found; run scripts/macos/generate_recover_icon.sh." >&2
fi

cat > "${APP_DIR}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleExecutable</key>
    <string>nyx_bkp_recover</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2026 Nyx Software, LLC</string>
</dict>
</plist>
PLIST

echo "  Built ${APP_NAME}.app"

# ── Build payload root (just the .app, no /usr/local/lib install) ────────────
#
# Unlike the main NyxBackup installer the Recovery Tool intentionally has
# NO daemon, NO CLI/TUI symlink, NO LaunchDaemon plist and NO shared state
# directory.  It is a single GUI binary that launches the user's browser
# for OAuth flows and writes restored files to wherever the user picks.

PKG_ROOT="${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/root"
rm -rf "$PKG_ROOT"
mkdir -p "${PKG_ROOT}/Applications"
cp -R "$APP_DIR" "${PKG_ROOT}/Applications/"

# ── Sign binaries (optional) ─────────────────────────────────────────────────
# Same identity envelopes as the main package; see build_pkg_arm64.sh.
if [[ -n "${APPLE_SIGNING_IDENTITY:-}" ]]; then
    echo "Code-signing recovery .app with: $APPLE_SIGNING_IDENTITY"
    # WKWebView entitlements (Tauri 2-based app)
    # bundles that JIT and load frameworks at runtime.
    INSTALLER_DIR="${WORKSPACE_DIR}/installer/macos"
    ENTITLEMENTS="${INSTALLER_DIR}/entitlements.plist"
    if [[ ! -f "$ENTITLEMENTS" ]]; then
        echo "ERROR: $ENTITLEMENTS missing.  Hardened Runtime needs the" >&2
        echo "       WKWebView entitlements to be passed at sign time." >&2
        exit 1
    fi
    codesign --force --options runtime --timestamp --deep \
        --entitlements "$ENTITLEMENTS" \
        --sign "$APPLE_SIGNING_IDENTITY" \
        "${PKG_ROOT}/Applications/${APP_NAME}.app"
    echo "  .app signed."
else
    echo "  APPLE_SIGNING_IDENTITY not set - skipping code signing."
fi

# ── Build component pkg with relocation disabled ───────────────

COMPONENT_PKG="${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/NyxBackupRecovery-component.pkg"
COMPONENT_PLIST="${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/component.plist"

pkgbuild --analyze --root "$PKG_ROOT" "$COMPONENT_PLIST"

/usr/bin/python3 - "$COMPONENT_PLIST" <<'PY'
import plistlib, sys
path = sys.argv[1]
with open(path, 'rb') as f:
    data = plistlib.load(f)
for entry in data:
    entry['BundleIsRelocatable'] = False
    entry['BundleOverwriteAction'] = 'upgrade'
with open(path, 'wb') as f:
    plistlib.dump(data, f)
PY

pkgbuild \
    --root "$PKG_ROOT" \
    --component-plist "$COMPONENT_PLIST" \
    --identifier "${BUNDLE_ID}" \
    --version "${VERSION}" \
    --install-location "/" \
    "$COMPONENT_PKG"

echo "  Component pkg built."

# ── Build product .pkg ───────────────────────────────────────────────────────

mkdir -p "$DIST"
PRODUCT_PKG="${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/${PKG_NAME}.pkg"

PRODUCTBUILD_SIGN=()
if [[ -n "${APPLE_INSTALLER_IDENTITY:-}" ]]; then
    echo "Signing .pkg with: $APPLE_INSTALLER_IDENTITY"
    PRODUCTBUILD_SIGN=(--sign "$APPLE_INSTALLER_IDENTITY" --timestamp)
fi

productbuild \
    --synthesize \
    --package "$COMPONENT_PKG" \
    "${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/distribution-synth.xml"
productbuild \
    --distribution "${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}/distribution-synth.xml" \
    --package-path "${WORKSPACE_DIR}/target/macos-recover-pkg/${ARCH}" \
    ${PRODUCTBUILD_SIGN[@]+"${PRODUCTBUILD_SIGN[@]}"} \
    "$PRODUCT_PKG"

echo "  Product pkg built: $PRODUCT_PKG"

# ── Copy the .pkg into dist/ as the shippable artefact (no DMG wrapper) ──

FINAL_PKG="${DIST}/${PKG_NAME}.pkg"
cp "$PRODUCT_PKG" "$FINAL_PKG"

echo ""
echo "Recovery .pkg created: ${FINAL_PKG}  ($(du -sh "$FINAL_PKG" | cut -f1))"
echo ""

# ── Notarize (optional) - same flow as the main package ──────────────────────

NOTARYTOOL_AUTH=()
if [[ -n "${APPLE_KEYCHAIN_PROFILE:-}" ]]; then
    NOTARYTOOL_AUTH=(--keychain-profile "$APPLE_KEYCHAIN_PROFILE")
elif [[ -n "${APPLE_ID:-}" && -n "${APPLE_APP_PASSWORD:-}" && -n "${APPLE_TEAM_ID:-}" ]]; then
    NOTARYTOOL_AUTH=(
        --apple-id "$APPLE_ID"
        --password "$APPLE_APP_PASSWORD"
        --team-id  "$APPLE_TEAM_ID"
    )
fi

if [[ -n "${SKIP_NOTARIZE:-}" ]]; then
    echo "  SKIP_NOTARIZE set - skipping notarization."
elif [[ ${#NOTARYTOOL_AUTH[@]} -gt 0 ]]; then
    if [[ -z "${APPLE_SIGNING_IDENTITY:-}" || -z "${APPLE_INSTALLER_IDENTITY:-}" ]]; then
        echo "  Refusing to notarize an unsigned Recovery .pkg."
        echo "  Set BOTH APPLE_SIGNING_IDENTITY and APPLE_INSTALLER_IDENTITY,"
        echo "  or set SKIP_NOTARIZE=1 to bypass."
        exit 1
    fi
    echo "Submitting $FINAL_PKG for notarization..."
    if xcrun notarytool submit "$FINAL_PKG" "${NOTARYTOOL_AUTH[@]}" --wait; then
        echo "  Stapling notarization ticket..."
        xcrun stapler staple "$FINAL_PKG"
        echo "  Notarized and stapled."
    else
        echo "ERROR: notarytool submit failed." >&2
        exit 1
    fi
else
    echo "  No notarization credentials set; skipping notarization."
fi

echo ""
echo "Install (on Mac):"
echo "  1. Double-click ${PKG_NAME}.pkg"
echo "  2. Follow the installer."
echo "  3. Launch '/Applications/${APP_NAME}.app' to restore."
